### PR TITLE
only list running pods

### LINKED ISSUE #86: Goldpinger starts so quickly it often gets pods without IPs
Goldpinger starts quickly, which is good, but it has an interesting side effect: often when it first lists pods, kubernetes doesn't list their IPs. With the current implementation, it often takes 30 seconds to restart the updaters goroutines. During these initial 30 seconds, graph and metrics are unhealthy.

It would be good to enhance it, so that if the pods don't have IPs, we retry to get them quicker than on other kinds of errors.

### PR DESCRIPTION
**Pull request by rbtr**
Signed-off-by: Evan Baker <rbtr@users.noreply.github.com>

Fixes #86

Adds a field selector to the list pod opts so that we select only running pods. This prevents us from discovering a pod before it has an IP address for us to use as a ping target.

### CODE REVIEW

**Review by seeker89 — APPROVED** [review]
This an awesome tweak. Thanks so much @rbtr !

**Comment by rbtr** [comment]
@seeker89 we'd love an official release for this and IPv6 changes, when you get a chance 🙂

**Comment by seeker89** [comment]
Yup, will do via https://github.com/bloomberg/goldpinger/pull/108

**Comment by rbtr** [comment]
tyvm

**Comment by seeker89** [comment]
> tyvm

There you go: https://github.com/bloomberg/goldpinger/releases/tag/v3.3.0

**Pull request merged**
