### PR TITLE
Extend DNS resolver to include TCP and HTTP checks for external targets 

### PR DESCRIPTION
**Pull request by kitfoman**
Goldpinger can currently do DNS checks via `HOSTS_TO_RESOLVE`.  This aims to extend that functionality so it can also do L4/L7 tcp and http/s checks. 

**Breaking Changes**

Timeout types were changed from `int64` to  `time.Duration` in the configuration [here](https://github.com/bloomberg/goldpinger/pull/115/files#diff-eb9feef919d5750208fccacf0fb4c44e3a7eced2f28410f09fc98a399cb7afb5L42-R51).
The flags `ping-timeout-ms`, `check-timeout-ms` and `check-all-timeout-ms `were also changed accordingly.

 Backward compatibility was considered but there doesn't seem to be a nice way of accomplishing this.

### CODE REVIEW

**Comment by seeker89** [comment]
Hey @kitfoman - sorry for the delay, I finally got around to looking at this.

It's great, but I'm a little bit concerned about the backwards compatibility. How would you feel about keeping the old flags with -ms postfix for now, marking them as deprecated, and using those, unless the new ones (duration) are used?

Ideally we wouldn't break anyone.

The other thing I'm wondering is how to best reflect the new probes in the prometheus metrics.

**Comment by kitfoman** [comment]
Hey @seeker89  I just saw this.

> It's great, but I'm a little bit concerned about the backwards compatibility. How would you feel about keeping the old flags with -ms postfix for now, marking them as deprecated, and using those, unless the new ones (duration) are used?

That sounds reasonable to me. I'll make those changes. 

> The other thing I'm wondering is how to best reflect the new probes in the prometheus metrics.

Do you mean in addition to [these](https://github.com/bloomberg/goldpinger/pull/115/files#diff-96d8754890c5c9665de98c3b5d530ea574d30c1d325625df09408df0b6a281f6R106)?  We can include a histogram as well if we want to expose latency information. Is there anything else that would be useful?

**Comment by kitfoman** [comment]
> > It's great, but I'm a little bit concerned about the backwards compatibility. How would you feel about keeping the old flags with -ms postfix for now, marking them as deprecated, and using those, unless the new ones (duration) are used?
> 
@seeker89  does this seem okay? https://github.com/kitfoman/goldpinger/blob/add-external-probes/cmd/goldpinger/main.go#L147

**Comment by seeker89** [comment]
> > > It's great, but I'm a little bit concerned about the backwards compatibility. How would you feel about keeping the old flags with -ms postfix for now, marking them as deprecated, and using those, unless the new ones (duration) are used?
> 
> @seeker89 does this seem okay? https://github.com/kitfoman/goldpinger/blob/add-external-probes/cmd/goldpinger/main.go#L147

Yup, that's what I was thinking.

**Comment by seeker89** [comment]
Looks like the DCO bot is unhappy again - would you mind re-pushing with `-s`?

**Comment by seeker89** [comment]
Hey, [69708ba](https://github.com/bloomberg/goldpinger/pull/115/commits/69708ba2f55a0f7d02331972a20296d0c1f8f7c9) is still missing the `-s`...

**Comment by kitfoman** [comment]
> Hey, [69708ba](https://github.com/bloomberg/goldpinger/pull/115/commits/69708ba2f55a0f7d02331972a20296d0c1f8f7c9) is still missing the `-s`...

sorry I confused myself there. It should be good now

**Comment by ArjonBu** [comment]
Is this going to be merged?

**Comment by ArjonBu** [comment]
@seeker89 The new version hasn't been pushed yet to docker hub. Is it planned?

**Comment by kitfoman** [comment]
> @seeker89 The new version hasn't been pushed yet to docker hub. Is it planned?

No there was a compile time error that I somehow missed in the . Created a new PR to address this https://github.com/bloomberg/goldpinger/pull/121

**Comment by seeker89** [comment]
Pushed v3.6.1 just now - not sure how the CI didn’t fail before, but here it goes.

**Pull request merged**
