### PR TITLE
Pod name instead of pod ip

### PR DESCRIPTION
**Pull request by skamboj**
**Describe your changes**
#76 fixed an issue where the k8s API server would return an empty pod IP for a goldpinger pod that was crashing. However, since our pod selector is designed to return a mapping of pod IP addresses to host IP addresses, it would fail to handle situations where two or more nodes were bad and were failing to report a pod IP address. In that case only a single failing pod would be reported by the pod selector.

This PR changes the `SelectPods` function to return a mapping from the pod name to the GoldpingerPod struct containing both the pod and host IP addresses. It also uses the PodName instead of the PodIP to do the rendezvous hashing for pod selection. 

**Testing performed**
- [x] Tested locally
- [ ] Test on a large cluster with all working as expected
- [ ] Test on a large cluster with one broken pod
- [ ] Test on a large cluster with multiple bad nodes

**Additional context**
This is a breaking change so upgraded both the major version and the schema version. I'd vote to hold off on releasing this while I make changes to the logging and another PR on how the updater works.

### CODE REVIEW

**Comment by skamboj** [comment]
@seeker89 This is still a WiP but describes the general approach. Could use your help testing on a bigger cluster :)

**Comment by seeker89** [comment]
I had a read through it, it looks great. I'll take it for a proper spin on a larger cluster on Monday!

**Comment by skamboj** [comment]
@seeker89 So turns out I can't do a PR off of this branch but this should also make the v3 cut: https://github.com/skamboj/goldpinger/pull/1

**Review by seeker89 — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
