### PR TITLE
Add default namespace `default` to ServiceAccount definition in example yaml

### PR DESCRIPTION
**Pull request by abctaylor**
This is to catch the case where users find-replace the `default` namespace with another namespace (say, `goldpinger` but don't change it for the ServiceAccount definition.

*Issue number of the reported bug or feature request: #<number>*

**Describe your changes**
Added a `namespace` key under `metadata` with corresponding namespace (`default`) used elsewhere in the sample yaml.

**Testing performed**
Tested on prem, k8s 1.27 with `kubectl apply -f file.yaml`.

**Additional context**
N/A.

### CODE REVIEW

**Comment by skamboj** [comment]
Thank you so much for your contribution. This looks good. We do need a DCO before we can approve this - please see this link: https://github.com/bloomberg/goldpinger/blob/master/CONTRIBUTING.md#contribution-licensing for details.

**Comment by abctaylor** [comment]
@skamboj did I not already do it in my first commit? LMK if something is wrong syntactically:
image

**Comment by skamboj** [comment]
> @skamboj did I not already do it in my first commit? LMK if something is wrong syntactically: image

Sorry the reason it failed is given here: https://github.com/bloomberg/goldpinger/runs/23516585421

```
Commit sha: [bda1235](https://github.com/bloomberg/goldpinger/pull/142/commits/bda1235c406be80ee1c3fa6189b6d3c8dd193889), Author: ABC Taylor, Committer: ABC Taylor; Expected "ABC Taylor [abc@abctaylor.com](mailto:abc@abctaylor.com)", but got "Andrew Taylor [abc@abctaylor.com](mailto:abc@abctaylor.com)".
```

I think it was expecting `ABC Taylor` and got `Andrew Taylor` instead.

**Comment by abctaylor** [comment]
@skamboj I have now `--amend`ed the message.

**Review by skamboj — APPROVED** [review]
LGTM, :shipit:

**Pull request merged**
