### PR TITLE
Add simple healthz endpoint

### LINKED ISSUE #8: The REST API should have a health endpoint
Currently goldpinger's REST API doesn't have a `/healthz` endpoint, which is not ideal for a kubernetes service as you're forced to check `/` in a `(liveness|readiness)Probe`. This isn't a best practice, so a health endpoint should be added.

### PR DESCRIPTION
**Pull request by kaduev13**
Resolves #8

### CODE REVIEW

**Comment by kaduev13** [comment]
Looks like this is a default behavior of `go-swagger` – these whitespaces are for different options which were not generated. E.g. [there is a newline](https://github.com/bloomberg/goldpinger/pull/29/files#diff-9d602bddc0c9f61b06a9453d4f6bf6fcR40) because of this [go-swagger template](https://github.com/go-swagger/go-swagger/blob/master/generator/templates/client/parameter.gotmpl#L38). Actually, there is a possibility to override default templates for the `go-swagger`.

**Comment by twexler** [comment]
Yeah, I find that a bit annoying. It also took me a minute to realize that that was from generated code. The non-generated stuff looks okay to me, but I'll defer to @seeker89 for an approval/merge 'cause I'm not super familiar with swagger in go

**Comment by kaduev13** [comment]
Thanks, cool 😄

**Comment by seeker89** [comment]
@kaduev13 it looks great, thanks a lot for the contribution !

I'll take it for a proper spin when I get a sec 👍

**Comment by kaduev13** [comment]
@seeker89 fyi: I also removed the header from new autogenerated files in this PR

**Pull request merged**
