### PR TITLE
Allow offline usage of the UI

### PR DESCRIPTION
**Pull request by jpmondet**
Hello,

Following the issue #39, this PR tries to allow offline usage of the UI by getting rid of the CDNs dependencies.

Basically, it adds the JS scripts in `/static` and change the `index.html` accordingly as suggested here #39 by @seeker89 

I tested this PR and it looks ok for offline usage. I uploaded the image used for you to test it if you want to : `docker.io/jpmondet/goldpinger:1.2.0-offline-usage`

Hope it looks ok for you :-)  

And thanks for this project !

### CODE REVIEW

**Comment by seeker89** [comment]
Awesome, thank you for taking your time to do this, @jpmondet ! 👍 

One remark I have, is that similar to https://github.com/bloomberg/goldpinger/pull/24, it's probably better to use relative import paths to avoid issues with proxies.

**Comment by seeker89** [comment]
I'm also wondering how we could improve Travis setup to test that the UI loads all right.

**Comment by jpmondet** [comment]
> One remark I have, is that similar to #24, it's probably better to use relative import paths to avoid issues with proxies.

Alright, thanks ! I have modified the path accordingly !
However, I won't be able to test this modification before next week.

**Comment by seeker89** [comment]
I'm not sure what's going on with Travis - it seems to be stuck with this job, even when I'm clicking on re-run. Hmmm...

**Comment by seeker89** [comment]
OK, Travis is happy again now. Not sure what the hiccup was.

**Comment by jpmondet** [comment]
> OK, Travis is happy again now. Not sure what the hiccup was.

Great, thanks !

And I was able to try the last modification you asked today and it works like a charm :-)

**Comment by seeker89** [comment]
Hey @jpmondet so sorry, I've completely forgotten about this PR. I'll test it ASAP.

The CI is unhappy about one of the dependencies url failing intermittently, don't think it has anything to do with this PR.

**Pull request merged**
