### PR TITLE
[WORK IN PROGRESS] Multi-architecture builds for goldpinger

### PR DESCRIPTION
**Pull request by mtougeron**
*Issue number of the reported bug or feature request: #94*

**Describe your changes**
This does a multi-stage, multi-architecture build for goldpinger.

**Testing performed**
Docker build, pushed to internal repository, ran in kubernetes, verified metrics available.

**Additional context**
@seeker89 mentioned that they'll be moving to GH actions so I included an example setup of the action to build & publish on new tags. GH action hasn't been fully tested for the `-vendor` builds.

### CODE REVIEW

**Comment by mtougeron** [comment]
@seeker89 Hi, I just wanted to check in on how the GH actions migration was going and if you had a chance to review the approach I'm proposing in this PR. No rush/pressure, just checking in. :)

**Comment by seeker89** [comment]
Thanks for the nudge, it fell off of my radar! I blocked some time to review tomorrow. Appreciate your patience!

**Comment by seeker89** [comment]
OK, I'm gonna merge this in and then do a few tweaks to get the GH actions in place. Thanks so much!

**Comment by mtougeron** [comment]
awesome, thanks. g'luck and let me know if you have any Qs about the way I set them up.

**Pull request merged**
